source('loadfilterdata.R')
filterdata$Global_active_power <- as.numeric(as.character(filterdata$Global_active_power))
filterdata$Global_reactive_power <- as.numeric(as.character(filterdata$Global_reactive_power))
filterdata$Voltage <- as.numeric(as.character(filterdata$Voltage))
filterdata$Global_intensity <- as.numeric(as.character(filterdata$Global_intensity))
filterdata$dt <- paste(filterdata$Date, filterdata$Time)
filterdata$dt <- strptime(filterdata$dt, "%d/%m/%Y %H:%M:%S")
filterdata$Sub_metering_1 <- as.numeric(as.character(filterdata$Sub_metering_1))
filterdata$Sub_metering_2 <- as.numeric(as.character(filterdata$Sub_metering_2))
filterdata$Sub_metering_3 <- as.numeric(as.character(filterdata$Sub_metering_3))
png(file = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(filterdata$dt,filterdata$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(filterdata$dt,filterdata$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(filterdata$dt,filterdata$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(filterdata$dt, filterdata$Sub_metering_2, type="l", col="red")
lines(filterdata$dt, filterdata$Sub_metering_3, type="l", col="blue")
legend("topright", bty="n", lty=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(filterdata$dt,filterdata$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()